"""remove user api key columns

Revision ID: a417c58f4ee3
Revises: 
Create Date: 2025-11-10 23:02:15.108148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a417c58f4ee3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'encrypted_api_key')
    op.drop_column('users', 'uses_personal_key')
    op.drop_column('users', 'api_key_updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('api_key_updated_at', sa.DATETIME(), nullable=True))
    op.add_column('users', sa.Column('uses_personal_key', sa.BOOLEAN(), nullable=True))
    op.add_column('users', sa.Column('encrypted_api_key', sa.BLOB(), nullable=True))
    # ### end Alembic commands ###
